### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by aeiousy** [theADAMJR/2PG#10]
I have a Question How do I fix invalid key that pops up anytime i try to log in

**Comment by theADAMJR** [comment]
**Problem**: Cannot login to dashboard
`Invalid Key - Check console`

**Possible Fixes**:
- Client secret is incorrect and needs regenerating

**Comment by splatboydev** [comment]
ah yes, thx

**Comment by splatboydev** [comment]
never mind, doesn't fix.

**Comment by DnxiPlayNonDev** [comment]
The same happens to me

**Comment by wil2005-development** [comment]
I have the same issue. I have the client recret regenerating. Nothing is working for now. Have you a fix for this?

**Comment by wil2005-development** [comment]
I fix my issue, i did run npm install @2pg/oauth and now it its version : ^1.0.7 then it is working for me. I hope that this a fix is for you.
