### ISSUE TITLE
How to start Dashboard project & bot proj in one ubuntu server

### ISSUE THREAD

**Issue by ghost** [theADAMJR/2PG#15]
Hey! I got a question, how can I run a Dashboard project and a bot project on the same server (ubuntu server 20.04), if the projects are in different folders.
concurrently does not work, gives the error mongoose is not default import, if you fix it, then mongoose is default import, help!
Thanks in advance!

**Comment by theADAMJR** [comment]
You would host the API on its own, as it comes with a prebuilt dashboard.
